name: Django CI

on:
  commit:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install pipenv
        pipenv sync -d
        cp contrib/env-sample .env
    -before scripts:
      - psql -C "CREATE DATABASE testdb;" -U postgres
    - name: Rodando Sistema
      run:
        pipenv run pytest --cov




